It refere to method that creates dense vector representative of text that capture semantic meaning

In [1]:
pip install flair

Collecting flair
  Downloading flair-0.15.1-py3-none-any.whl.metadata (12 kB)
Collecting boto3>=1.20.27 (from flair)
  Downloading boto3-1.43.2-py3-none-any.whl.metadata (6.5 kB)
Collecting conllu<5.0.0,>=4.0 (from flair)
  Downloading conllu-4.5.3-py2.py3-none-any.whl.metadata (19 kB)
Collecting deprecated>=1.2.13 (from flair)
  Downloading deprecated-1.3.1-py2.py3-none-any.whl.metadata (5.9 kB)
Collecting ftfy>=6.1.0 (from flair)
  Downloading ftfy-6.3.1-py3-none-any.whl.metadata (7.3 kB)
Collecting gdown>=4.4.0 (from flair)
  Downloading gdown-6.0.0-py3-none-any.whl.metadata (7.4 kB)
Collecting huggingface-hub>=0.10.0 (from flair)
  Downloading huggingface_hub-1.13.0-py3-none-any.whl.metadata (14 kB)
Collecting langdetect>=1.0.9 (from flair)
  Downloading langdetect-1.0.9.tar.gz (981 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 981.5/981.5 kB 3.3 MB/s  0:00:00eta 0:00:01
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting lxml>=4.8.0 (from flair)
  Downloading lxml-6.1.0-cp312-cp312-macosx_10_13_universal2.whl.metadata (4.0 kB)
Requirement already satisfied: matplotlib>=2.2.3 in /Users/rahulg/.pyenv/versions/3.12.4/lib/python3.12/site-packages (from flair) (3.10.8)
Collecting more-itertools>=8.13.0 (from flair)
  Downloading more_itertools-11.0.2-py3-none-any.whl.metadata (41 kB)
Collecting mpld3>=0.3 (from flair)
  Downloading mpld3-0.5.12-py3-none-any.whl.metadata (5.3 kB)
Collecting pptree>=3.1 (from flair)
  Downloading pptree-3.1.tar.gz (3.0 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/rahulg/.pyenv/versions/3.12.4/lib/python3.12/site-packages (from flair) (2.9.0.post0)
Collecting pytorch-revgrad>=0.2.0 (from flair)
  Downloading pytorch_revgrad-0.2.0-py3-none-any.whl.metadata (1.7 kB)
Requirement already satisfied: regex>=2022.1.18 in /Users/rahulg/.pyenv/versions/3.12.4/lib/python3.12/site-packages (from flair) (2026.4.4)
Requirement already satisfied: scikit-learn>=1.0.2 in /Users/rahulg/.pyenv/versions/3.12.4/lib/python3.12/site-packages (from flair) (1.8.0)
Collecting segtok>=1.5.11 (from flair)
  Downloading segtok-1.5.11-py3-none-any.whl.metadata (9.0 kB)
Collecting sqlitedict>=2.0.0 (from flair)
  Downloading sqlitedict-2.1.0.tar.gz (21 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting tabulate>=0.8.10 (from flair)
  Downloading tabulate-0.10.0-py3-none-any.whl.metadata (40 kB)
Requirement already satisfied: torch>=1.13.1 in /Users/rahulg/.pyenv/versions/3.12.4/lib/python3.12/site-packages (from flair) (2.10.0)
Requirement already satisfied: tqdm>=4.63.0 in /Users/rahulg/.pyenv/versions/3.12.4/lib/python3.12/site-packages (from flair) (4.67.3)
Collecting transformer-smaller-training-vocab>=0.2.3 (from flair)
  Downloading transformer_smaller_training_vocab-0.4.2-py3-none-any.whl.metadata (7.9 kB)
Collecting transformers<5.0.0,>=4.25.0 (from transformers[sentencepiece]<5.0.0,>=4.25.0->flair)
  Downloading transformers-4.57.6-py3-none-any.whl.metadata (43 kB)
Collecting wikipedia-api>=0.5.7 (from flair)
  Downloading wikipedia_api-0.14.1-py3-none-any.whl.metadata (43 kB)
Collecting bioc<3.0.0,>=2.0.0 (from flair)
  Downloading bioc-2.1-py3-none-any.whl.metadata (4.6 kB)
Collecting jsonlines>=1.2.0 (from bioc<3.0.0,>=2.0.0->flair)
  Downloading jsonlines-4.0.0-py3-none-any.whl.metadata (1.6 kB)
Collecting intervaltree (from bioc<3.0.0,>=2.0.0->flair)
  Downloading intervaltree-3.2.1-py2.py3-none-any.whl.metadata (12 kB)
Collecting docopt (from bioc<3.0.0,>=2.0.0->flair)
  Downloading docopt-0.6.2.tar.gz (25 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: filelock in /Users/rahulg/.pyenv/versions/3.12.4/lib/python3.12/site-packages (from transformers<5.0.0,>=4.25.0->transformers[sentencepiece]<5.0.0,>=4.25.0->flair) (3.24.3)
Collecting huggingface-hub>=0.10.0 (from flair)
  Downloading huggingface_hub-0.36.2-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: numpy>=1.17 in /Users/rahulg/.pyenv/versions/3.12.4/lib/python3.12/site-packages (from transformers<5.0.0,>=4.25.0->transformers[sentencepiece]<5.0.0,>=4.25.0->flair) (2.4.2)
Requirement already satisfied: packaging>=20.0 in /Users/rahulg/.pyenv/versions/3.12.4/lib/python3.12/site-packages (from transformers<5.0.0,>=4.25.0->transformers[sentencepiece]<5.0.0,>=4.25.0->flair) (26.0)
Collecting pyyaml>=5.1 (from transformers<5.0.0,>=4.25.0->transformers[sentencepiece]<5.0.0,>=4.25.0->flair)
  Downloading pyyaml-6.0.3-cp312-cp312-macosx_11_0_arm64.whl.metadata (2.4 kB)
Requirement already satisfied: requests in /Users/rahulg/.pyenv/versions/3.12.4/lib/python3.12/site-packages (from transformers<5.0.0,>=4.25.0->transformers[sentencepiece]<5.0.0,>=4.25.0->flair) (2.32.5)
Collecting tokenizers<=0.23.0,>=0.22.0 (from transformers<5.0.0,>=4.25.0->transformers[sentencepiece]<5.0.0,>=4.25.0->flair)
  Downloading tokenizers-0.22.2-cp39-abi3-macosx_11_0_arm64.whl.metadata (7.3 kB)
Collecting safetensors>=0.4.3 (from transformers<5.0.0,>=4.25.0->transformers[sentencepiece]<5.0.0,>=4.25.0->flair)
  Downloading safetensors-0.7.0-cp38-abi3-macosx_11_0_arm64.whl.metadata (4.1 kB)
Requirement already satisfied: fsspec>=2023.5.0 in /Users/rahulg/.pyenv/versions/3.12.4/lib/python3.12/site-packages (from huggingface-hub>=0.10.0->flair) (2026.2.0)
Collecting hf-xet<2.0.0,>=1.1.3 (from huggingface-hub>=0.10.0->flair)
  Downloading hf_xet-1.4.3-cp37-abi3-macosx_11_0_arm64.whl.metadata (4.9 kB)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /Users/rahulg/.pyenv/versions/3.12.4/lib/python3.12/site-packages (from huggingface-hub>=0.10.0->flair) (4.15.0)
Collecting sentencepiece!=0.1.92,>=0.1.91 (from transformers[sentencepiece]<5.0.0,>=4.25.0->flair)
  Downloading sentencepiece-0.2.1-cp312-cp312-macosx_11_0_arm64.whl.metadata (10 kB)
Requirement already satisfied: protobuf in /Users/rahulg/.pyenv/versions/3.12.4/lib/python3.12/site-packages (from transformers[sentencepiece]<5.0.0,>=4.25.0->flair) (7.34.0)
Collecting botocore<1.44.0,>=1.43.2 (from boto3>=1.20.27->flair)
  Downloading botocore-1.43.2-py3-none-any.whl.metadata (5.5 kB)
Collecting jmespath<2.0.0,>=0.7.1 (from boto3>=1.20.27->flair)
  Downloading jmespath-1.1.0-py3-none-any.whl.metadata (7.6 kB)
Collecting s3transfer<0.18.0,>=0.17.0 (from boto3>=1.20.27->flair)
  Downloading s3transfer-0.17.0-py3-none-any.whl.metadata (1.7 kB)
Requirement already satisfied: urllib3!=2.2.0,<3,>=1.25.4 in /Users/rahulg/.pyenv/versions/3.12.4/lib/python3.12/site-packages (from botocore<1.44.0,>=1.43.2->boto3>=1.20.27->flair) (2.6.3)
Requirement already satisfied: six>=1.5 in /Users/rahulg/.pyenv/versions/3.12.4/lib/python3.12/site-packages (from python-dateutil>=2.8.2->flair) (1.17.0)
Requirement already satisfied: wrapt<3,>=1.10 in /Users/rahulg/.pyenv/versions/3.12.4/lib/python3.12/site-packages (from deprecated>=1.2.13->flair) (2.1.1)
Requirement already satisfied: wcwidth in /Users/rahulg/.pyenv/versions/3.12.4/lib/python3.12/site-packages (from ftfy>=6.1.0->flair) (0.6.0)
Collecting beautifulsoup4 (from gdown>=4.4.0->flair)
  Downloading beautifulsoup4-4.14.3-py3-none-any.whl.metadata (3.8 kB)
Collecting attrs>=19.2.0 (from jsonlines>=1.2.0->bioc<3.0.0,>=2.0.0->flair)
  Downloading attrs-26.1.0-py3-none-any.whl.metadata (8.8 kB)
Requirement already satisfied: contourpy>=1.0.1 in /Users/rahulg/.pyenv/versions/3.12.4/lib/python3.12/site-packages (from matplotlib>=2.2.3->flair) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /Users/rahulg/.pyenv/versions/3.12.4/lib/python3.12/site-packages (from matplotlib>=2.2.3->flair) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /Users/rahulg/.pyenv/versions/3.12.4/lib/python3.12/site-packages (from matplotlib>=2.2.3->flair) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /Users/rahulg/.pyenv/versions/3.12.4/lib/python3.12/site-packages (from matplotlib>=2.2.3->flair) (1.4.9)
Requirement already satisfied: pillow>=8 in /Users/rahulg/.pyenv/versions/3.12.4/lib/python3.12/site-packages (from matplotlib>=2.2.3->flair) (12.1.1)
Requirement already satisfied: pyparsing>=3 in /Users/rahulg/.pyenv/versions/3.12.4/lib/python3.12/site-packages (from matplotlib>=2.2.3->flair) (3.3.2)
Requirement already satisfied: jinja2 in /Users/rahulg/.pyenv/versions/3.12.4/lib/python3.12/site-packages (from mpld3>=0.3->flair) (3.1.6)
Requirement already satisfied: scipy>=1.10.0 in /Users/rahulg/.pyenv/versions/3.12.4/lib/python3.12/site-packages (from scikit-learn>=1.0.2->flair) (1.17.1)
Requirement already satisfied: joblib>=1.3.0 in /Users/rahulg/.pyenv/versions/3.12.4/lib/python3.12/site-packages (from scikit-learn>=1.0.2->flair) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in /Users/rahulg/.pyenv/versions/3.12.4/lib/python3.12/site-packages (from scikit-learn>=1.0.2->flair) (3.6.0)
Requirement already satisfied: setuptools in /Users/rahulg/.pyenv/versions/3.12.4/lib/python3.12/site-packages (from torch>=1.13.1->flair) (82.0.0)
Requirement already satisfied: sympy>=1.13.3 in /Users/rahulg/.pyenv/versions/3.12.4/lib/python3.12/site-packages (from torch>=1.13.1->flair) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /Users/rahulg/.pyenv/versions/3.12.4/lib/python3.12/site-packages (from torch>=1.13.1->flair) (3.6.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /Users/rahulg/.pyenv/versions/3.12.4/lib/python3.12/site-packages (from sympy>=1.13.3->torch>=1.13.1->flair) (1.3.0)
Collecting accelerate>=0.26.0 (from transformers<5.0.0,>=4.25.0->transformers[sentencepiece]<5.0.0,>=4.25.0->flair)
  Downloading accelerate-1.13.0-py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: psutil in /Users/rahulg/.pyenv/versions/3.12.4/lib/python3.12/site-packages (from accelerate>=0.26.0->transformers<5.0.0,>=4.25.0->transformers[sentencepiece]<5.0.0,>=4.25.0->flair) (7.2.2)
Collecting click==8.3.2 (from wikipedia-api>=0.5.7->flair)
  Downloading click-8.3.2-py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: httpx==0.28.1 in /Users/rahulg/.pyenv/versions/3.12.4/lib/python3.12/site-packages (from wikipedia-api>=0.5.7->flair) (0.28.1)
Collecting tenacity==9.1.4 (from wikipedia-api>=0.5.7->flair)
  Downloading tenacity-9.1.4-py3-none-any.whl.metadata (1.2 kB)
Requirement already satisfied: anyio in /Users/rahulg/.pyenv/versions/3.12.4/lib/python3.12/site-packages (from httpx==0.28.1->wikipedia-api>=0.5.7->flair) (4.13.0)
Requirement already satisfied: certifi in /Users/rahulg/.pyenv/versions/3.12.4/lib/python3.12/site-packages (from httpx==0.28.1->wikipedia-api>=0.5.7->flair) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /Users/rahulg/.pyenv/versions/3.12.4/lib/python3.12/site-packages (from httpx==0.28.1->wikipedia-api>=0.5.7->flair) (1.0.9)
Requirement already satisfied: idna in /Users/rahulg/.pyenv/versions/3.12.4/lib/python3.12/site-packages (from httpx==0.28.1->wikipedia-api>=0.5.7->flair) (3.11)
Requirement already satisfied: h11>=0.16 in /Users/rahulg/.pyenv/versions/3.12.4/lib/python3.12/site-packages (from httpcore==1.*->httpx==0.28.1->wikipedia-api>=0.5.7->flair) (0.16.0)
Collecting soupsieve>=1.6.1 (from beautifulsoup4->gdown>=4.4.0->flair)
  Downloading soupsieve-2.8.3-py3-none-any.whl.metadata (4.6 kB)
Collecting sortedcontainers (from intervaltree->bioc<3.0.0,>=2.0.0->flair)
  Downloading sortedcontainers-2.4.0-py2.py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: MarkupSafe>=2.0 in /Users/rahulg/.pyenv/versions/3.12.4/lib/python3.12/site-packages (from jinja2->mpld3>=0.3->flair) (3.0.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /Users/rahulg/.pyenv/versions/3.12.4/lib/python3.12/site-packages (from requests->transformers<5.0.0,>=4.25.0->transformers[sentencepiece]<5.0.0,>=4.25.0->flair) (3.4.4)
Collecting PySocks!=1.5.7,>=1.5.6 (from requests[socks]->gdown>=4.4.0->flair)
  Downloading PySocks-1.7.1-py3-none-any.whl.metadata (13 kB)
Downloading flair-0.15.1-py3-none-any.whl (1.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 1.7 MB/s  0:00:00 eta 0:00:01
Downloading bioc-2.1-py3-none-any.whl (33 kB)
Downloading conllu-4.5.3-py2.py3-none-any.whl (16 kB)
Downloading transformers-4.57.6-py3-none-any.whl (12.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.0/12.0 MB 6.0 MB/s  0:00:02 eta 0:00:01
Downloading huggingface_hub-0.36.2-py3-none-any.whl (566 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 566.4/566.4 kB 5.7 MB/s  0:00:00
Downloading hf_xet-1.4.3-cp37-abi3-macosx_11_0_arm64.whl (3.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.6/3.6 MB 5.7 MB/s  0:00:00 eta 0:00:01
Downloading tokenizers-0.22.2-cp39-abi3-macosx_11_0_arm64.whl (3.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.0/3.0 MB 5.5 MB/s  0:00:00 eta 0:00:01
Downloading boto3-1.43.2-py3-none-any.whl (140 kB)
Downloading botocore-1.43.2-py3-none-any.whl (15.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.0/15.0 MB 4.8 MB/s  0:00:03m0:00:0100:01
Downloading jmespath-1.1.0-py3-none-any.whl (20 kB)
Downloading s3transfer-0.17.0-py3-none-any.whl (86 kB)
Downloading deprecated-1.3.1-py2.py3-none-any.whl (11 kB)
Downloading ftfy-6.3.1-py3-none-any.whl (44 kB)
Downloading gdown-6.0.0-py3-none-any.whl (18 kB)
Downloading jsonlines-4.0.0-py3-none-any.whl (8.7 kB)
Downloading attrs-26.1.0-py3-none-any.whl (67 kB)
Downloading lxml-6.1.0-cp312-cp312-macosx_10_13_universal2.whl (8.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.6/8.6 MB 5.9 MB/s  0:00:01m0:00:0100:01
Downloading more_itertools-11.0.2-py3-none-any.whl (71 kB)
Downloading mpld3-0.5.12-py3-none-any.whl (203 kB)
Downloading pytorch_revgrad-0.2.0-py3-none-any.whl (4.6 kB)
Downloading pyyaml-6.0.3-cp312-cp312-macosx_11_0_arm64.whl (173 kB)
Downloading safetensors-0.7.0-cp38-abi3-macosx_11_0_arm64.whl (447 kB)
Downloading segtok-1.5.11-py3-none-any.whl (24 kB)
Downloading sentencepiece-0.2.1-cp312-cp312-macosx_11_0_arm64.whl (1.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 5.7 MB/s  0:00:00 eta 0:00:01
Downloading tabulate-0.10.0-py3-none-any.whl (39 kB)
Downloading transformer_smaller_training_vocab-0.4.2-py3-none-any.whl (14 kB)
Downloading accelerate-1.13.0-py3-none-any.whl (383 kB)
Downloading wikipedia_api-0.14.1-py3-none-any.whl (129 kB)
Downloading click-8.3.2-py3-none-any.whl (108 kB)
Downloading tenacity-9.1.4-py3-none-any.whl (28 kB)
Downloading beautifulsoup4-4.14.3-py3-none-any.whl (107 kB)
Downloading soupsieve-2.8.3-py3-none-any.whl (37 kB)
Downloading intervaltree-3.2.1-py2.py3-none-any.whl (25 kB)
Downloading PySocks-1.7.1-py3-none-any.whl (16 kB)
Downloading sortedcontainers-2.4.0-py2.py3-none-any.whl (29 kB)
Building wheels for collected packages: langdetect, pptree, sqlitedict, docopt
  Building wheel for langdetect (pyproject.toml) ... done
  Created wheel for langdetect: filename=langdetect-1.0.9-py3-none-any.whl size=993332 sha256=aa934c929b7d7dacaf12df491e78a4ce2cc20948ce4e24f172f8cef4f8687de9
  Stored in directory: /Users/rahulg/Library/Caches/pip/wheels/c1/67/88/e844b5b022812e15a52e4eaa38a1e709e99f06f6639d7e3ba7
  Building wheel for pptree (pyproject.toml) ... done
  Created wheel for pptree: filename=pptree-3.1-py3-none-any.whl size=4640 sha256=6ef9e08ba7522557333aadd8e90567ccafb0de9f16e3175fa74a65c7aae966be
  Stored in directory: /Users/rahulg/Library/Caches/pip/wheels/b0/2d/de/37058114a8f07cfec75747cb46b864bc5c71b0e9e0e4cd0acd
  Building wheel for sqlitedict (pyproject.toml) ... done
  Created wheel for sqlitedict: filename=sqlitedict-2.1.0-py3-none-any.whl size=16955 sha256=ec0e38b93c08c70fb43d71df059024d42b21938483a5a382d148ab188de43625
  Stored in directory: /Users/rahulg/Library/Caches/pip/wheels/7a/6f/21/fc016aef45ffcabe27129a2252f061387cbf278d2086225a64
  Building wheel for docopt (pyproject.toml) ... done
  Created wheel for docopt: filename=docopt-0.6.2-py2.py3-none-any.whl size=13782 sha256=149e61c22819b732165940f49c8649960f2c67e6c9227fe372dc87b2fc5ebb69
  Stored in directory: /Users/rahulg/Library/Caches/pip/wheels/1a/bf/a1/4cee4f7678c68c5875ca89eaccf460593539805c3906722228
Successfully built langdetect pptree sqlitedict docopt
Installing collected packages: sqlitedict, sortedcontainers, pptree, docopt, tenacity, tabulate, soupsieve, sentencepiece, segtok, safetensors, pyyaml, PySocks, more-itertools, lxml, langdetect, jmespath, intervaltree, hf-xet, ftfy, deprecated, conllu, click, attrs, jsonlines, huggingface-hub, botocore, beautifulsoup4, wikipedia-api, tokenizers, s3transfer, pytorch-revgrad, mpld3, gdown, bioc, accelerate, transformers, boto3, transformer-smaller-training-vocab, flair
  Attempting uninstall: clickm╺━━━━━━━━━━━━━━━━━━━━━━━━━━ 13/39 [lxml]
    Found existing installation: click 8.3.3━━━━━━━━━━━━━━━━━━ 13/39 [lxml]
    Uninstalling click-8.3.3:0m━━━━━━━━━━━━━━━━━━━━━━━━━━ 13/39 [lxml]
      Successfully uninstalled click-8.3.3━━━━━━━━━━━━━━━━━━━━ 13/39 [lxml]
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 39/39 [flair]m38/39 [flair]ormers]ub]
Successfully installed PySocks-1.7.1 accelerate-1.13.0 attrs-26.1.0 beautifulsoup4-4.14.3 bioc-2.1 boto3-1.43.2 botocore-1.43.2 click-8.3.2 conllu-4.5.3 deprecated-1.3.1 docopt-0.6.2 flair-0.15.1 ftfy-6.3.1 gdown-6.0.0 hf-xet-1.4.3 huggingface-hub-0.36.2 intervaltree-3.2.1 jmespath-1.1.0 jsonlines-4.0.0 langdetect-1.0.9 lxml-6.1.0 more-itertools-11.0.2 mpld3-0.5.12 pptree-3.1 pytorch-revgrad-0.2.0 pyyaml-6.0.3 s3transfer-0.17.0 safetensors-0.7.0 segtok-1.5.11 sentencepiece-0.2.1 sortedcontainers-2.4.0 soupsieve-2.8.3 sqlitedict-2.1.0 tabulate-0.10.0 tenacity-9.1.4 tokenizers-0.22.2 transformer-smaller-training-vocab-0.4.2 transformers-4.57.6 wikipedia-api-0.14.1

[notice] A new release of pip is available: 26.0.1 -> 26.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [3]:
from flair.models import TextClassifier
from flair.data import Sentence

classifier = TextClassifier.load('en-sentiment')

2026-05-02 19:37:47,773 https://nlp.informatik.hu-berlin.de/resources/models/sentiment-curated-distilbert/sentiment-en-mix-distillbert_4.pt not found in cache, downloading to /var/folders/l0/yk46hdzn3tgb8l9p047d0bkm0000gn/T/tmp9c2_jyfi

100%|██████████| 253M/253M [12:42<00:00, 348kB/s]

2026-05-02 19:50:30,607 copying /var/folders/l0/yk46hdzn3tgb8l9p047d0bkm0000gn/T/tmp9c2_jyfi to cache at /Users/rahulg/.flair/models/sentiment-en-mix-distillbert_4.pt

2026-05-02 19:50:30,752 removing temp file /var/folders/l0/yk46hdzn3tgb8l9p047d0bkm0000gn/T/tmp9c2_jyfi

In [4]:
import pandas as pd

In [11]:
sentences = [
    "I absolutely loved the new Batman movie",
    "The food was cold and tasteless",
    "It was an average experience, nothing special",
    "I am very excited to start my new job tomorrow",
    "The Phone is terrible I regret buying it",
    "The staff were friendly and helpful",
    "Its raining heavily, What a dull day",
    "The app keeps crashing Its so annoying",
    "Nothing went according to my plan today",
    "The equipment is operating, but occasionally it makes noise."
]

In [14]:
res = []

for text in sentences:
    sent = Sentence(text)   # ✅ use text here
    classifier.predict(sent)
    
    label = sent.labels[0]
    
    res.append({            # ✅ correct method
        'Sentence': text,
        'Sentiment': label.value,
        'Confidence': round(label.score, 4)
    })

df = pd.DataFrame(res)
df

                                            Sentence Sentiment  Confidence
0            I absolutely loved the new Batman movie  POSITIVE      0.9970
1                    The food was cold and tasteless  NEGATIVE      1.0000
2      It was an average experience, nothing special  NEGATIVE      1.0000
3     I am very excited to start my new job tomorrow  POSITIVE      0.9970
4           The Phone is terrible I regret buying it  NEGATIVE      1.0000
5                The staff were friendly and helpful  POSITIVE      0.9705
6               Its raining heavily, What a dull day  NEGATIVE      0.9998
7             The app keeps crashing Its so annoying  NEGATIVE      0.9990
8            Nothing went according to my plan today  NEGATIVE      0.9921
9  The equipment is operating, but occasionally i...  NEGATIVE      0.9975

after using the transformer pipeline see the difference

In [18]:
pip install tf-keras

Collecting tf-keras
  Downloading tf_keras-2.21.0-py3-none-any.whl.metadata (1.8 kB)
Collecting tensorflow<2.22,>=2.21 (from tf-keras)
  Downloading tensorflow-2.21.0-cp312-cp312-macosx_12_0_arm64.whl.metadata (4.4 kB)
Requirement already satisfied: absl-py>=1.0.0 in /Users/rahulg/.pyenv/versions/3.12.4/lib/python3.12/site-packages (from tensorflow<2.22,>=2.21->tf-keras) (2.4.0)
Requirement already satisfied: astunparse>=1.6.0 in /Users/rahulg/.pyenv/versions/3.12.4/lib/python3.12/site-packages (from tensorflow<2.22,>=2.21->tf-keras) (1.6.3)
Requirement already satisfied: flatbuffers>=25.9.23 in /Users/rahulg/.pyenv/versions/3.12.4/lib/python3.12/site-packages (from tensorflow<2.22,>=2.21->tf-keras) (25.12.19)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in /Users/rahulg/.pyenv/versions/3.12.4/lib/python3.12/site-packages (from tensorflow<2.22,>=2.21->tf-keras) (0.7.0)
Requirement already satisfied: google_pasta>=0.1.1 in /Users/rahulg/.pyenv/versions/3.12.4/lib/python3.12/site-packages (from tensorflow<2.22,>=2.21->tf-keras) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in /Users/rahulg/.pyenv/versions/3.12.4/lib/python3.12/site-packages (from tensorflow<2.22,>=2.21->tf-keras) (18.1.1)
Requirement already satisfied: opt_einsum>=2.3.2 in /Users/rahulg/.pyenv/versions/3.12.4/lib/python3.12/site-packages (from tensorflow<2.22,>=2.21->tf-keras) (3.4.0)
Requirement already satisfied: packaging in /Users/rahulg/.pyenv/versions/3.12.4/lib/python3.12/site-packages (from tensorflow<2.22,>=2.21->tf-keras) (26.0)
Requirement already satisfied: protobuf<8.0.0,>=6.31.1 in /Users/rahulg/.pyenv/versions/3.12.4/lib/python3.12/site-packages (from tensorflow<2.22,>=2.21->tf-keras) (7.34.0)
Requirement already satisfied: requests<3,>=2.21.0 in /Users/rahulg/.pyenv/versions/3.12.4/lib/python3.12/site-packages (from tensorflow<2.22,>=2.21->tf-keras) (2.32.5)
Requirement already satisfied: setuptools in /Users/rahulg/.pyenv/versions/3.12.4/lib/python3.12/site-packages (from tensorflow<2.22,>=2.21->tf-keras) (82.0.0)
Requirement already satisfied: six>=1.12.0 in /Users/rahulg/.pyenv/versions/3.12.4/lib/python3.12/site-packages (from tensorflow<2.22,>=2.21->tf-keras) (1.17.0)
Requirement already satisfied: termcolor>=1.1.0 in /Users/rahulg/.pyenv/versions/3.12.4/lib/python3.12/site-packages (from tensorflow<2.22,>=2.21->tf-keras) (3.3.0)
Requirement already satisfied: typing_extensions>=3.6.6 in /Users/rahulg/.pyenv/versions/3.12.4/lib/python3.12/site-packages (from tensorflow<2.22,>=2.21->tf-keras) (4.15.0)
Requirement already satisfied: wrapt>=1.11.0 in /Users/rahulg/.pyenv/versions/3.12.4/lib/python3.12/site-packages (from tensorflow<2.22,>=2.21->tf-keras) (2.1.1)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in /Users/rahulg/.pyenv/versions/3.12.4/lib/python3.12/site-packages (from tensorflow<2.22,>=2.21->tf-keras) (1.78.0)
Requirement already satisfied: keras>=3.12.0 in /Users/rahulg/.pyenv/versions/3.12.4/lib/python3.12/site-packages (from tensorflow<2.22,>=2.21->tf-keras) (3.13.2)
Requirement already satisfied: numpy>=1.26.0 in /Users/rahulg/.pyenv/versions/3.12.4/lib/python3.12/site-packages (from tensorflow<2.22,>=2.21->tf-keras) (2.4.2)
Collecting h5py<3.15.0,>=3.11.0 (from tensorflow<2.22,>=2.21->tf-keras)
  Downloading h5py-3.14.0-cp312-cp312-macosx_11_0_arm64.whl.metadata (2.7 kB)
Requirement already satisfied: ml_dtypes<1.0.0,>=0.5.1 in /Users/rahulg/.pyenv/versions/3.12.4/lib/python3.12/site-packages (from tensorflow<2.22,>=2.21->tf-keras) (0.5.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /Users/rahulg/.pyenv/versions/3.12.4/lib/python3.12/site-packages (from requests<3,>=2.21.0->tensorflow<2.22,>=2.21->tf-keras) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /Users/rahulg/.pyenv/versions/3.12.4/lib/python3.12/site-packages (from requests<3,>=2.21.0->tensorflow<2.22,>=2.21->tf-keras) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/rahulg/.pyenv/versions/3.12.4/lib/python3.12/site-packages (from requests<3,>=2.21.0->tensorflow<2.22,>=2.21->tf-keras) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in /Users/rahulg/.pyenv/versions/3.12.4/lib/python3.12/site-packages (from requests<3,>=2.21.0->tensorflow<2.22,>=2.21->tf-keras) (2026.2.25)
Requirement already satisfied: wheel<1.0,>=0.23.0 in /Users/rahulg/.pyenv/versions/3.12.4/lib/python3.12/site-packages (from astunparse>=1.6.0->tensorflow<2.22,>=2.21->tf-keras) (0.46.3)
Requirement already satisfied: rich in /Users/rahulg/.pyenv/versions/3.12.4/lib/python3.12/site-packages (from keras>=3.12.0->tensorflow<2.22,>=2.21->tf-keras) (14.3.3)
Requirement already satisfied: namex in /Users/rahulg/.pyenv/versions/3.12.4/lib/python3.12/site-packages (from keras>=3.12.0->tensorflow<2.22,>=2.21->tf-keras) (0.1.0)
Requirement already satisfied: optree in /Users/rahulg/.pyenv/versions/3.12.4/lib/python3.12/site-packages (from keras>=3.12.0->tensorflow<2.22,>=2.21->tf-keras) (0.19.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /Users/rahulg/.pyenv/versions/3.12.4/lib/python3.12/site-packages (from rich->keras>=3.12.0->tensorflow<2.22,>=2.21->tf-keras) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /Users/rahulg/.pyenv/versions/3.12.4/lib/python3.12/site-packages (from rich->keras>=3.12.0->tensorflow<2.22,>=2.21->tf-keras) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /Users/rahulg/.pyenv/versions/3.12.4/lib/python3.12/site-packages (from markdown-it-py>=2.2.0->rich->keras>=3.12.0->tensorflow<2.22,>=2.21->tf-keras) (0.1.2)
Downloading tf_keras-2.21.0-py3-none-any.whl (1.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 8.6 MB/s  0:00:00 eta 0:00:01
Downloading tensorflow-2.21.0-cp312-cp312-macosx_12_0_arm64.whl (223.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 223.5/223.5 MB 1.8 MB/s  0:01:51m0:00:0100:04
Downloading h5py-3.14.0-cp312-cp312-macosx_11_0_arm64.whl (2.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.8/2.8 MB 4.6 MB/s  0:00:00 eta 0:00:01
Installing collected packages: h5py, tensorflow, tf-keras
  Attempting uninstall: h5py
    Found existing installation: h5py 3.15.1
    Uninstalling h5py-3.15.1:
      Successfully uninstalled h5py-3.15.1
  Attempting uninstall: tensorflow
    Found existing installation: tensorflow 2.20.0
    Uninstalling tensorflow-2.20.0:━━━━━━━━━━━━━━━━━━━━━━━━━━ 1/3 [tensorflow]
      Successfully uninstalled tensorflow-2.20.0━━━━━━━━━━━━━━━━━━ 1/3 [tensorflow]
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3/3 [tf-keras]2/3 [tf-keras]w]
Successfully installed h5py-3.14.0 tensorflow-2.21.0 tf-keras-2.21.0

[notice] A new release of pip is available: 26.0.1 -> 26.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [19]:
from transformers import pipeline

In [21]:
pip install torch

Requirement already satisfied: torch in /Users/rahulg/.pyenv/versions/3.12.4/lib/python3.12/site-packages (2.10.0)
Requirement already satisfied: filelock in /Users/rahulg/.pyenv/versions/3.12.4/lib/python3.12/site-packages (from torch) (3.24.3)
Requirement already satisfied: typing-extensions>=4.10.0 in /Users/rahulg/.pyenv/versions/3.12.4/lib/python3.12/site-packages (from torch) (4.15.0)
Requirement already satisfied: setuptools in /Users/rahulg/.pyenv/versions/3.12.4/lib/python3.12/site-packages (from torch) (82.0.0)
Requirement already satisfied: sympy>=1.13.3 in /Users/rahulg/.pyenv/versions/3.12.4/lib/python3.12/site-packages (from torch) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /Users/rahulg/.pyenv/versions/3.12.4/lib/python3.12/site-packages (from torch) (3.6.1)
Requirement already satisfied: jinja2 in /Users/rahulg/.pyenv/versions/3.12.4/lib/python3.12/site-packages (from torch) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /Users/rahulg/.pyenv/versions/3.12.4/lib/python3.12/site-packages (from torch) (2026.2.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /Users/rahulg/.pyenv/versions/3.12.4/lib/python3.12/site-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /Users/rahulg/.pyenv/versions/3.12.4/lib/python3.12/site-packages (from jinja2->torch) (3.0.3)

[notice] A new release of pip is available: 26.0.1 -> 26.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [26]:
from transformers import pipeline

classifier = pipeline("sentiment-analysis", framework="pt")

In [27]:
result = []

output = classifier(sentences)

for text,output in zip(sentences,output):
    res.append({            # ✅ correct method
        'Sentence': text,
        'Sentiment': label.value,
        'Confidence': round(label.score, 4)
    })

df1 = pd.DataFrame(result)
df1

Empty DataFrame
Columns: []
Index: []

In [29]:
pip install nrclex

Collecting nrclex
  Downloading nrclex-4.1.0-py3-none-any.whl.metadata (2.7 kB)
Requirement already satisfied: textblob>=0.17 in /Users/rahulg/.pyenv/versions/3.12.4/lib/python3.12/site-packages (from nrclex) (0.20.0)
Requirement already satisfied: nltk>=3.9 in /Users/rahulg/.pyenv/versions/3.12.4/lib/python3.12/site-packages (from textblob>=0.17->nrclex) (3.9.4)
Requirement already satisfied: click in /Users/rahulg/.pyenv/versions/3.12.4/lib/python3.12/site-packages (from nltk>=3.9->textblob>=0.17->nrclex) (8.3.2)
Requirement already satisfied: joblib in /Users/rahulg/.pyenv/versions/3.12.4/lib/python3.12/site-packages (from nltk>=3.9->textblob>=0.17->nrclex) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in /Users/rahulg/.pyenv/versions/3.12.4/lib/python3.12/site-packages (from nltk>=3.9->textblob>=0.17->nrclex) (2026.4.4)
Requirement already satisfied: tqdm in /Users/rahulg/.pyenv/versions/3.12.4/lib/python3.12/site-packages (from nltk>=3.9->textblob>=0.17->nrclex) (4.67.3)
Downloading nrclex-4.1.0-py3-none-any.whl (44 kB)
Installing collected packages: nrclex
Successfully installed nrclex-4.1.0

[notice] A new release of pip is available: 26.0.1 -> 26.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [32]:
from nrclex import NRCLex

In [37]:
import nltk
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to
[nltk_data]     /Users/rahulg/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [38]:
text = " I am furious and deeply disappointed"
emotions = NRCLex(text)

In [44]:
from nrclex import NRCLex

text = "I am furious and deeply disappointed"
emotions = NRCLex(text)

print(type(emotions))
print(dir(emotions))

<class 'nrclex.core.NRCLex'>
['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lexicon__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_build_word_affect', '_compute_top_emotions', '_resolve_lexicon', 'load_raw_text', 'load_token_list']